import { Domain, Item, Module, Quiz, Cohort, User } from './types';

export const ADMIN_USERS: User[] = [
  { id: 'admin1', name: 'Sarah Admin', email: 'sarah@skills.com', role: 'ADMIN' },
  { id: 'editor1', name: 'Mike Editor', email: 'mike@skills.com', role: 'EDITOR' },
];

export const CONTRIBUTOR_USERS: User[] = [
  { id: 'contrib1', name: 'Taylor Contributor', email: 'taylor@skills.com', role: 'CONTRIBUTOR' },
];

export const COHORTS: Cohort[] = [
  {
    id: 'c_summer_23',
    name: 'Summer 2023 Intake',
    courseIds: ['short_sc_1', 'short_fitbiz_1'],
    userIds: ['u1'],
    startDate: '2023-11-01',
    status: 'ACTIVE'
  },
  {
    id: 'c_winter_24',
    name: 'Winter 2024 Intake',
    courseIds: ['short_sc_1'],
    userIds: [],
    startDate: '2024-06-01',
    status: 'UPCOMING'
  }
];

export const DOMAINS: Domain[] = [
  { id: 'dom_sc', name: 'Strength & Conditioning', partners: ['ASCA', 'Talent Locker', 'Daniel McTainsh ©', 'Nick Graham'] },
  { id: 'dom_nut', name: 'Nutrition', partners: ['Bass Yaghi', 'Kia Moini'] },
  { id: 'dom_fitbiz', name: 'Fitness Business', partners: ['Brad Davis', 'Aus Active', 'Affiliates?', 'Christian David', 'Brent Hutchinson'] },
  { id: 'dom_online', name: 'Online Coaching', partners: ['Meg Tovey Fitness', 'Christian David'] },
  { id: 'dom_ai', name: 'AI in Fitness', partners: [] },
  { id: 'dom_mh', name: 'Mental Health & Fitness', partners: ['Aus Active', 'Paul Nichols (HHL)'] },
  { id: 'dom_mind', name: 'Mindset Coaching', partners: ['Carlos Chincarini', 'Kia/Nina Moini?'] },
  { id: 'dom_health', name: 'Typical Health Conditions', partners: [] },
  { id: 'dom_women', name: 'Women Specific Training', partners: ['Mairi Thompson', 'Jessica Furmage ©'] },
  { id: 'dom_disability', name: 'Disability Support', partners: ['Inclusive AF', 'FIT Care'] },
  { id: 'dom_func', name: 'Functional Fitness', partners: ['Josh Wood*©'] },
  { id: 'dom_hyper', name: 'Advanced Hypertrophy', partners: ['Nick Graham'] },
  { id: 'dom_power', name: 'Power Training', partners: ['Carly Smit', 'Wayne Willis', 'Nick Graham', 'Cam Muir'] },
  { id: 'dom_sport', name: 'Sport Coaching', partners: ['Neil Odell'] },
  { id: 'dom_outdoor', name: 'Outdoor Group Training', partners: ['Josh Jones'] }
];

const RAW_ITEMS: Omit<Item, 'status' | 'versionNumber'>[] = [
  // --- Strength & Conditioning ---
  {
    id: 'byte_sc_1',
    domainId: 'dom_sc',
    tier: 'BYTE',
    title: 'A Career in S&C (ASCA)',
    description: 'Explore the professional pathways and standards within Strength & Conditioning.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Understand industry standards', 'Identify career paths', 'Learn ASCA role'],
    prerequisites: [],
    popularityScore: 88,
    image: '/images/courses/Heading (1).png',
    price: 0
  },
  {
    id: 'byte_sc_2',
    domainId: 'dom_sc',
    tier: 'BYTE',
    title: 'Supercompensation',
    description: 'Master the cycle of training stress, recovery, and performance adaptation.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Define supercompensation', 'Map training cycles', 'Optimize timing'],
    prerequisites: ['byte_sc_1'],
    popularityScore: 92,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'byte_sc_3',
    domainId: 'dom_sc',
    tier: 'BYTE',
    title: 'Deload, recovery, adaptation week',
    description: 'Strategic recovery planning to prevent burnout and maximize gains.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Plan deloads', 'Recognize overtraining', 'Structure recovery'],
    prerequisites: ['byte_sc_2'],
    popularityScore: 85,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'byte_sc_4',
    domainId: 'dom_sc',
    tier: 'BYTE',
    title: 'Coaching skills e.g. cues external/internal',
    description: 'Enhance your coaching verbal and visual cueing for better athlete performance.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Use external cues', 'Refine internal cues', 'Improve communication'],
    prerequisites: ['byte_sc_3'],
    popularityScore: 90,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'micro_sc_1',
    domainId: 'dom_sc',
    tier: 'MICROCRED',
    title: 'Micros, Mesos & Macros',
    description: 'Comprehensive guide to periodization cycles and planning structures.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Design macrocycles', 'Structure mesocycles', 'Plan microcycles'],
    prerequisites: ['byte_sc_4'],
    popularityScore: 94,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_sc_2',
    domainId: 'dom_sc',
    tier: 'MICROCRED',
    title: 'Energy Systems in Training',
    description: 'Deep dive into ATP-PC, Glycolytic, and Aerobic systems in sport.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Identify energy demands', 'Program intervals', 'Assess capacity'],
    prerequisites: ['micro_sc_1'],
    popularityScore: 89,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_sc_3',
    domainId: 'dom_sc',
    tier: 'MICROCRED',
    title: 'Strength in S&C',
    description: 'Foundations of strength development and programming.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Program for strength', 'Teach main lifts', 'Ensure safety'],
    prerequisites: ['micro_sc_2'],
    popularityScore: 91,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_sc_4',
    domainId: 'dom_sc',
    tier: 'MICROCRED',
    title: 'Speed-Endurance in S&C',
    description: 'Training methodologies for speed maintenance and repeatability.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Drill speed mechanics', 'Build endurance', 'Monitor fatigue'],
    prerequisites: ['micro_sc_3'],
    popularityScore: 87,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_sc_5',
    domainId: 'dom_sc',
    tier: 'MICROCRED',
    title: 'Athletic Skill in S&C',
    description: 'Developing agility, balance, and coordination in athletes.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Coach agility', 'Improve balance', 'Enhance coordination'],
    prerequisites: ['micro_sc_4'],
    popularityScore: 86,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_sc_6',
    domainId: 'dom_sc',
    tier: 'MICROCRED',
    title: 'Recovery in S&C',
    description: 'Evidence-based recovery protocols for high performance.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Implement protocols', 'Advise on sleep', 'Manage nutrition'],
    prerequisites: ['micro_sc_5'],
    popularityScore: 93,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'short_sc_1',
    domainId: 'dom_sc',
    tier: 'SHORT',
    title: 'Periodisation & Planning',
    description: 'Mastery level course on long-term athletic development and annual planning.',
    durationLabel: '1–3 weeks',
    accredited: false,
    outcomes: ['Create annual plans', 'Manage athlete loads', 'Adjust for competition', 'Present periodization models'],
    prerequisites: ['micro_sc_1', 'micro_sc_2'],
    popularityScore: 98,
    image: '/images/courses/Heading (3).png',
    price: 499
  },

  // --- Nutrition ---
  {
    id: 'byte_nut_1',
    domainId: 'dom_nut',
    tier: 'BYTE',
    title: 'TDEE & Energy Basics',
    description: 'Understanding Total Daily Energy Expenditure and BMR.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Calculate TDEE', 'Explain energy balance', 'Assess metabolism'],
    prerequisites: [],
    popularityScore: 85,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'micro_nut_1',
    domainId: 'dom_nut',
    tier: 'MICROCRED',
    title: 'How to Calculate Macro\'s',
    description: 'Practical skills for setting macronutrient targets.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Set protein targets', 'Balance fats/carbs', 'Adjust for goals'],
    prerequisites: ['byte_nut_1'],
    popularityScore: 90,
    image: '/images/courses/Heading (2).png',
    price: 120
  },
  {
    id: 'micro_nut_2',
    domainId: 'dom_nut',
    tier: 'MICROCRED',
    title: 'Protein grams per kgs',
    description: 'Optimizing protein intake for different populations.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Recommend intake', 'Understand synthesis', 'Source quality protein'],
    prerequisites: ['micro_nut_1'],
    popularityScore: 88,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_nut_3',
    domainId: 'dom_nut',
    tier: 'MICROCRED',
    title: 'Glycemic index, load',
    description: 'Understanding carbohydrate quality and blood sugar impact.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Explain GI/GL', 'Choose carb sources', 'Time nutrient intake'],
    prerequisites: ['micro_nut_2'],
    popularityScore: 84,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'short_nut_1',
    domainId: 'dom_nut',
    tier: 'SHORT',
    title: 'Nutrition for Fat Loss',
    description: 'Advanced strategies for sustainable weight management.',
    durationLabel: '1–3 weeks',
    accredited: false,
    outcomes: ['Design fat loss phases', 'Manage diet breaks', 'Support behavior change', 'Monitor progress'],
    prerequisites: ['micro_nut_1', 'micro_nut_2'],
    popularityScore: 95,
    image: '/images/courses/Heading (3).png',
    price: 499
  },
  {
    id: 'short_nut_2',
    domainId: 'dom_nut',
    tier: 'SHORT',
    title: 'Nutrition for Hypertrophy',
    description: 'Nutritional protocols to support muscle growth and recovery.',
    durationLabel: '1–3 weeks',
    accredited: false,
    outcomes: ['Fuel for growth', 'Optimize post-workout', 'Supplement wisely', 'Adjust surplus'],
    prerequisites: ['micro_nut_1', 'micro_nut_2'],
    popularityScore: 94,
    image: '/images/courses/Heading (3).png',
    price: 499
  },

  // --- Fitness Business ---
  {
    id: 'byte_fitbiz_1',
    domainId: 'dom_fitbiz',
    tier: 'BYTE',
    title: 'The Sole Trader PT (C4)',
    description: 'Essentials of setting up as a sole trader in the fitness industry.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Understand legalities', 'Manage taxes basics', 'Set rates'],
    prerequisites: [],
    popularityScore: 82,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'byte_fitbiz_2',
    domainId: 'dom_fitbiz',
    tier: 'BYTE',
    title: 'Employment Opportunities in Fitness (C3)',
    description: 'Navigating the job market and career paths in fitness.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Identify roles', 'Prepare resume', 'Ace interviews'],
    prerequisites: ['byte_fitbiz_1'],
    popularityScore: 80,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'byte_fitbiz_3',
    domainId: 'dom_fitbiz',
    tier: 'BYTE',
    title: 'My niche/market',
    description: 'Identifying and defining your ideal client avatar.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Define avatar', 'Analyze market', 'Position services'],
    prerequisites: ['byte_fitbiz_2'],
    popularityScore: 85,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'micro_fitbiz_1',
    domainId: 'dom_fitbiz',
    tier: 'MICROCRED',
    title: 'Setting up your Fitness Business',
    description: 'Step-by-step guide to launching your fitness brand.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Register business', 'Set up banking', 'Create brand identity'],
    prerequisites: ['byte_fitbiz_3'],
    popularityScore: 88,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_fitbiz_2',
    domainId: 'dom_fitbiz',
    tier: 'MICROCRED',
    title: 'Business tools & tech (whoop etc)',
    description: 'Leveraging technology for efficiency and client results.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Select software', 'Use wearables', 'Automate tasks'],
    prerequisites: ['micro_fitbiz_1'],
    popularityScore: 86,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_fitbiz_3',
    domainId: 'dom_fitbiz',
    tier: 'MICROCRED',
    title: 'How to get, and keep clients',
    description: 'Sales and retention strategies for a thriving business.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Generate leads', 'Close sales', 'Improve retention'],
    prerequisites: ['micro_fitbiz_2'],
    popularityScore: 92,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_fitbiz_4',
    domainId: 'dom_fitbiz',
    tier: 'MICROCRED',
    title: 'Your first 12 weeks as a new PT',
    description: 'A roadmap for surviving and thriving in your first quarter.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Set 90-day goals', 'Build client base', 'Establish routine'],
    prerequisites: ['micro_fitbiz_3'],
    popularityScore: 89,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_fitbiz_5',
    domainId: 'dom_fitbiz',
    tier: 'MICROCRED',
    title: 'Building a long term Career',
    description: 'Strategies for longevity and preventing burnout.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Plan career path', 'Manage work-life', 'Diversify income'],
    prerequisites: ['micro_fitbiz_4'],
    popularityScore: 87,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'short_fitbiz_1',
    domainId: 'dom_fitbiz',
    tier: 'SHORT',
    title: 'Systemised Personal Training',
    description: 'Creating scalable systems for high-quality service delivery.',
    durationLabel: '1–3 weeks',
    accredited: false,
    outcomes: ['Build SOPs', 'Scale operations', 'Hire staff', 'Automate marketing'],
    prerequisites: ['micro_fitbiz_1', 'micro_fitbiz_2'],
    popularityScore: 93,
    image: '/images/courses/Heading (3).png',
    price: 499
  },

  // --- Online Coaching ---
  {
    id: 'byte_online_1',
    domainId: 'dom_online',
    tier: 'BYTE',
    title: 'Should I start an Online Fitness business',
    description: 'Assessing feasibility and readiness for online coaching.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Analyze market', 'Assess skills', 'Determine costs'],
    prerequisites: [],
    popularityScore: 88,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'micro_online_1',
    domainId: 'dom_online',
    tier: 'MICROCRED',
    title: 'Effective Client Communication Online',
    description: 'Mastering digital communication to build rapport and trust.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Use video feedback', 'Manage check-ins', 'Build community'],
    prerequisites: ['byte_online_1'],
    popularityScore: 89,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_online_2',
    domainId: 'dom_online',
    tier: 'MICROCRED',
    title: 'Creating Engaging Online Products & Services',
    description: 'Designing digital products that deliver results and engagement.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Design challenges', 'Create content', 'Structure programs'],
    prerequisites: ['micro_online_1'],
    popularityScore: 87,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_online_3',
    domainId: 'dom_online',
    tier: 'MICROCRED',
    title: 'Pricing & Packaging Your Online Services',
    description: 'Strategies for profitable and attractive pricing models.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Determine pricing', 'Create packages', 'Handle objections'],
    prerequisites: ['micro_online_2'],
    popularityScore: 90,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_online_4',
    domainId: 'dom_online',
    tier: 'MICROCRED',
    title: 'Retention & Growth Strategies for Online PTs',
    description: 'Keeping clients longer and growing your digital footprint.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Boost retention', 'Gather testimonials', 'Upsell services'],
    prerequisites: ['micro_online_3'],
    popularityScore: 91,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'short_online_1',
    domainId: 'dom_online',
    tier: 'SHORT',
    title: 'Success in Online Coaching',
    description: 'Complete blueprint for a successful and scalable online business.',
    durationLabel: '1–3 weeks',
    accredited: false,
    outcomes: ['Launch business', 'Scale ads', 'Automate delivery', 'Build brand'],
    prerequisites: ['micro_online_1', 'micro_online_2'],
    popularityScore: 96,
    image: '/images/courses/Heading (3).png',
    price: 499
  },

  // --- AI in Fitness ---
  {
    id: 'byte_ai_1',
    domainId: 'dom_ai',
    tier: 'BYTE',
    title: 'The rise of AI - What it means for Fitness',
    description: 'Understanding the impact of artificial intelligence on the fitness industry.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Define AI in fitness', 'Identify trends', 'Assess opportunities'],
    prerequisites: [],
    popularityScore: 95,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'byte_ai_2',
    domainId: 'dom_ai',
    tier: 'BYTE',
    title: 'How it can be used',
    description: 'Practical applications of AI tools for trainers and businesses.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Use chatbots', 'Automate admin', 'Personalize plans'],
    prerequisites: ['byte_ai_1'],
    popularityScore: 92,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'byte_ai_3',
    domainId: 'dom_ai',
    tier: 'BYTE',
    title: 'Why use it time vs money, systems',
    description: 'Analyzing the ROI of integrating AI into your workflow.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Calculate ROI', 'Optimize systems', 'Save time'],
    prerequisites: ['byte_ai_2'],
    popularityScore: 89,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'micro_ai_1',
    domainId: 'dom_ai',
    tier: 'MICROCRED',
    title: 'AI for Program Design & Tracking',
    description: 'Using AI to generate training programs and analyze client data.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Generate programs', 'Analyze progress', 'Adapt variables'],
    prerequisites: ['byte_ai_3'],
    popularityScore: 94,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_ai_2',
    domainId: 'dom_ai',
    tier: 'MICROCRED',
    title: 'Implementing AI in Your Fitness Business',
    description: 'Strategic integration of AI for business growth and efficiency.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Integrate tools', 'Scale operations', 'Enhance service'],
    prerequisites: ['micro_ai_1'],
    popularityScore: 91,
    image: '/images/courses/Heading (3).png',
    price: 120
  },

  // --- Mental Health & Fitness ---
  {
    id: 'byte_mh_1',
    domainId: 'dom_mh',
    tier: 'BYTE',
    title: 'Role of Exercise in Common Mental Health conditions',
    description: 'How physical activity impacts mental well-being and pathology.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Explain benefits', 'Understand conditions', 'Apply safety'],
    prerequisites: [],
    popularityScore: 90,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'byte_mh_2',
    domainId: 'dom_mh',
    tier: 'BYTE',
    title: 'Basic signs symptoms (part of mental health FA)',
    description: 'Recognizing early warning signs of mental health struggles.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Identify signs', 'Approach clients', 'Listen actively'],
    prerequisites: ['byte_mh_1'],
    popularityScore: 88,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'byte_mh_3',
    domainId: 'dom_mh',
    tier: 'BYTE',
    title: 'Mental health conditions examples',
    description: 'Overview of anxiety, depression, and other common conditions.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Define anxiety', 'Define depression', 'Understand scope'],
    prerequisites: ['byte_mh_2'],
    popularityScore: 87,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'byte_mh_4',
    domainId: 'dom_mh',
    tier: 'BYTE',
    title: 'Referral services',
    description: 'Building a referral network and knowing when to refer.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Build network', 'Refer effectively', 'Maintain boundaries'],
    prerequisites: ['byte_mh_3'],
    popularityScore: 85,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'micro_mh_1',
    domainId: 'dom_mh',
    tier: 'MICROCRED',
    title: 'Mental Health Basics for PTs',
    description: 'Foundational mental health literacy for fitness professionals.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Apply first aid', 'Create safe space', 'Communicate empathy'],
    prerequisites: ['byte_mh_4'],
    popularityScore: 92,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_mh_2',
    domainId: 'dom_mh',
    tier: 'MICROCRED',
    title: 'Managing Anxiety & Depression with Exercise',
    description: 'Exercise programming specifically for mood disorders.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Program for mood', 'Adjust intensity', 'Monitor response'],
    prerequisites: ['micro_mh_1'],
    popularityScore: 91,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_mh_3',
    domainId: 'dom_mh',
    tier: 'MICROCRED',
    title: 'Building Mental Resilience Through Training',
    description: 'Using training challenges to build psychological hardiness.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Coach resilience', 'Set challenges', 'Debrief sessions'],
    prerequisites: ['micro_mh_2'],
    popularityScore: 89,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_mh_4',
    domainId: 'dom_mh',
    tier: 'MICROCRED',
    title: 'Self Care, Relaxation',
    description: 'Techniques for stress management and trainer self-care.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Teach relaxation', 'Practice self-care', 'Manage burnout'],
    prerequisites: ['micro_mh_3'],
    popularityScore: 86,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'short_mh_1',
    domainId: 'dom_mh',
    tier: 'SHORT',
    title: 'Mental Health First Aid (NRT)',
    description: 'Accredited certification in Mental Health First Aid.',
    durationLabel: '1–3 weeks',
    accredited: false,
    outcomes: ['Recognize crises', 'Respond to suicide', 'Support recovery', 'Apply ALGEE'],
    prerequisites: ['micro_mh_1', 'micro_mh_2'],
    popularityScore: 96,
    image: '/images/courses/Heading (3).png',
    price: 499
  },

  // --- Mindset Coaching ---
  {
    id: 'byte_mind_1',
    domainId: 'dom_mind',
    tier: 'BYTE',
    title: 'The role of Mindset Training in PT',
    description: 'Why mindset is the key driver of physical results.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Define mindset', 'Connect to results', 'Integrate into PT'],
    prerequisites: [],
    popularityScore: 88,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'byte_mind_2',
    domainId: 'dom_mind',
    tier: 'BYTE',
    title: 'Resilience Case Studies: Jocko & Goggins',
    description: 'Analyzing extreme ownership and discipline models.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Analyze discipline', 'Apply ownership', 'Teach resilience'],
    prerequisites: ['byte_mind_1'],
    popularityScore: 93,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'byte_mind_3',
    domainId: 'dom_mind',
    tier: 'BYTE',
    title: 'Measuring client\'s motivation',
    description: 'Tools and scales to assess client readiness and drive.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Assess readiness', 'Use scales', 'Identify drivers'],
    prerequisites: ['byte_mind_2'],
    popularityScore: 86,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'byte_mind_4',
    domainId: 'dom_mind',
    tier: 'BYTE',
    title: 'Personality types',
    description: 'Tailoring your coaching style to different personalities.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Identify types', 'Adapt style', 'Improve rapport'],
    prerequisites: ['byte_mind_3'],
    popularityScore: 89,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'micro_mind_1',
    domainId: 'dom_mind',
    tier: 'MICROCRED',
    title: 'Behavioural Change Techniques for PTs',
    description: 'Psychological strategies to foster lasting habit change.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Apply CBT basics', 'Facilitate change', 'Overcome barriers'],
    prerequisites: ['byte_mind_4'],
    popularityScore: 91,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_mind_2',
    domainId: 'dom_mind',
    tier: 'MICROCRED',
    title: 'Enhancing Motivation in Clients',
    description: 'Moving clients from extrinsic to intrinsic motivation.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Build autonomy', 'Foster mastery', 'Set effective goals'],
    prerequisites: ['micro_mind_1'],
    popularityScore: 90,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_mind_3',
    domainId: 'dom_mind',
    tier: 'MICROCRED',
    title: 'The Science of Habit Formation',
    description: 'Neuroscience of building and breaking habits.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Explain habit loops', 'Design cues', 'Stack habits'],
    prerequisites: ['micro_mind_2'],
    popularityScore: 89,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_mind_4',
    domainId: 'dom_mind',
    tier: 'MICROCRED',
    title: 'Performance Psychology for Trainers',
    description: 'Mental skills training for peak performance.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Visualize success', 'Manage arousal', 'Focus attention'],
    prerequisites: ['micro_mind_3'],
    popularityScore: 88,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_mind_5',
    domainId: 'dom_mind',
    tier: 'MICROCRED',
    title: 'Neuro-Linguistic Programming (NLP) Basics',
    description: 'Introduction to NLP techniques for powerful communication.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Use reframing', 'Anchor states', 'Mirror and match'],
    prerequisites: ['micro_mind_4'],
    popularityScore: 87,
    image: '/images/courses/Heading (3).png',
    price: 120
  },

  // --- Typical Health Conditions ---
  {
    id: 'byte_health_1',
    domainId: 'dom_health',
    tier: 'BYTE',
    title: 'How Common are typical Health conditons',
    description: 'Prevalence and epidemiology of chronic diseases.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Cite statistics', 'Understand impact', 'Identify trends'],
    prerequisites: [],
    popularityScore: 84,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'byte_health_2',
    domainId: 'dom_health',
    tier: 'BYTE',
    title: 'Defining health (Vs fitness)',
    description: 'Distinguishing between health metrics and performance metrics.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Define wellness', 'Contrast fitness', 'Holistic view'],
    prerequisites: ['byte_health_1'],
    popularityScore: 86,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'micro_health_1',
    domainId: 'dom_health',
    tier: 'MICROCRED',
    title: 'The Obesity Epidemic',
    description: 'Pathophysiology and management of obesity through exercise.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Understand causes', 'Program for weight loss', 'Address stigma'],
    prerequisites: ['byte_health_2'],
    popularityScore: 90,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_health_2',
    domainId: 'dom_health',
    tier: 'MICROCRED',
    title: 'Hypertension & CVD',
    description: 'Exercise guidelines for high blood pressure and heart disease.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Modify intensity', 'Monitor contraindications', 'Improve heart health'],
    prerequisites: ['micro_health_1'],
    popularityScore: 89,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_health_3',
    domainId: 'dom_health',
    tier: 'MICROCRED',
    title: 'COPD',
    description: 'Safe training for Chronic Obstructive Pulmonary Disease.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Manage dyspnea', 'Improve capacity', 'Ensure safety'],
    prerequisites: ['micro_health_2'],
    popularityScore: 87,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_health_4',
    domainId: 'dom_health',
    tier: 'MICROCRED',
    title: 'Musculoskeletal Conditions',
    description: 'Exercise for arthritis, osteoporosis, and back pain.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Modify for pain', 'Strengthen joints', 'Prevent falls'],
    prerequisites: ['micro_health_3'],
    popularityScore: 91,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_health_5',
    domainId: 'dom_health',
    tier: 'MICROCRED',
    title: 'Metabolic Conditions',
    description: 'Management of diabetes and metabolic syndrome.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Manage blood sugar', 'Program for insulin', 'Reduce risk'],
    prerequisites: ['micro_health_4'],
    popularityScore: 92,
    image: '/images/courses/Heading (3).png',
    price: 120
  },

  // --- Women Specific Training ---
  {
    id: 'byte_women_1',
    domainId: 'dom_women',
    tier: 'BYTE',
    title: 'Is it safe to train while Pregnant',
    description: 'Guidelines and contraindications for training during pregnancy.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Identify risks', 'Modify exercises', 'Ensure safety'],
    prerequisites: [],
    popularityScore: 94,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'byte_women_2',
    domainId: 'dom_women',
    tier: 'BYTE',
    title: 'How the hormone cycle affects energy & performance',
    description: 'Understanding menstrual cycle phases and their impact on training.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Track cycle phases', 'Adjust intensity', 'Optimize performance'],
    prerequisites: ['byte_women_1'],
    popularityScore: 93,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'micro_women_1',
    domainId: 'dom_women',
    tier: 'MICROCRED',
    title: 'Cycle based Training for Woman',
    description: 'Designing training programs that align with female physiology.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Program for phases', 'Manage fatigue', 'Support recovery'],
    prerequisites: ['byte_women_2'],
    popularityScore: 91,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_women_2',
    domainId: 'dom_women',
    tier: 'MICROCRED',
    title: 'Hormonal Conditions - PCOS , Endometriosis, Amenhorrhea',
    description: 'Training considerations for common hormonal conditions.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Understand PCOS', 'Manage endometriosis symptoms', 'Support hormonal health'],
    prerequisites: ['micro_women_1'],
    popularityScore: 90,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_women_3',
    domainId: 'dom_women',
    tier: 'MICROCRED',
    title: 'Pre & Post Natal Training',
    description: 'Specialized programming for clients before and after childbirth.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Screen clients', 'Program safely', 'Restore core function'],
    prerequisites: ['micro_women_2'],
    popularityScore: 95,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'short_women_1',
    domainId: 'dom_women',
    tier: 'SHORT',
    title: 'Women Specific Training (Includes Pre Post Natal)',
    description: 'Comprehensive certification in female-specific training.',
    durationLabel: '1–3 weeks',
    accredited: false,
    outcomes: ['Master female physiology', 'Specialize in women\'s fitness', 'Build client base', 'Create safe environments'],
    prerequisites: ['micro_women_1', 'micro_women_2'],
    popularityScore: 97,
    image: '/images/courses/Heading (3).png',
    price: 499
  },

  // --- Disability Support ---
  {
    id: 'byte_disability_1',
    domainId: 'dom_disability',
    tier: 'BYTE',
    title: 'Tommy\'s Byte',
    description: 'Introduction to disability support in fitness.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Understand disability', 'Learn terminology', 'Respect autonomy'],
    prerequisites: [],
    popularityScore: 85,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'byte_disability_2',
    domainId: 'dom_disability',
    tier: 'BYTE',
    title: 'Making a positive impact, how an help, rewarding',
    description: 'The rewards and methods of working with disabled populations.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Identify impact', 'Engage effectively', 'Build inclusive habits'],
    prerequisites: ['byte_disability_1'],
    popularityScore: 88,
    image: '/images/courses/Heading (3).png',
    price: 0
  },

  // --- Functional Fitness ---
  {
    id: 'byte_func_1',
    domainId: 'dom_func',
    tier: 'BYTE',
    title: 'Intro to Boxing (Why boxing in Fitness)',
    description: 'Basics of boxing for fitness clients.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Wrap hands', 'Throw basic punches', 'Ensure safety'],
    prerequisites: [],
    popularityScore: 92,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'byte_func_2',
    domainId: 'dom_func',
    tier: 'BYTE',
    title: 'Intro to Suspension (Proprioception and Levers)',
    description: 'Understanding suspension training mechanics.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Set up straps', 'Understand leverage', 'Modify difficulty'],
    prerequisites: ['byte_func_1'],
    popularityScore: 89,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'byte_func_3',
    domainId: 'dom_func',
    tier: 'BYTE',
    title: 'Intro to KB (Swing Variations)',
    description: 'Foundational kettlebell movements and safety.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Teach the swing', 'Correct form', 'Select weights'],
    prerequisites: ['byte_func_2'],
    popularityScore: 91,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'byte_func_4',
    domainId: 'dom_func',
    tier: 'BYTE',
    title: 'Intro to Battle Rope (Benefits)',
    description: 'Incorporating battle ropes for conditioning.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Use waves/slams', 'Program intervals', 'Coach intensity'],
    prerequisites: ['byte_func_3'],
    popularityScore: 85,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'byte_func_5',
    domainId: 'dom_func',
    tier: 'BYTE',
    title: 'Intro to Resistance Bands (Application of Bands)',
    description: 'Versatile training with resistance bands.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Select bands', 'Modify exercises', 'Add resistance'],
    prerequisites: ['byte_func_4'],
    popularityScore: 87,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'byte_func_6',
    domainId: 'dom_func',
    tier: 'BYTE',
    title: 'Intro to Mace Training (Benefits)',
    description: 'Basics of steel mace training for flow and stability.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Hold a mace', 'Perform 360s', 'Build grip strength'],
    prerequisites: ['byte_func_5'],
    popularityScore: 83,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'micro_func_1',
    domainId: 'dom_func',
    tier: 'MICROCRED',
    title: 'Shadow Box Techniques (Exercises)',
    description: 'Advanced shadow boxing drills and combinations.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Build combos', 'Improve footwork', 'Increase cardio'],
    prerequisites: ['byte_func_6'],
    popularityScore: 90,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_func_2',
    domainId: 'dom_func',
    tier: 'MICROCRED',
    title: 'Suspension Techniques (Exercises)',
    description: 'Advanced suspension exercises for strength and stability.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Advance progressions', 'Coach suspension', 'Build core strength'],
    prerequisites: ['micro_func_1'],
    popularityScore: 88,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_func_3',
    domainId: 'dom_func',
    tier: 'MICROCRED',
    title: 'KB Techniques (Exercises)',
    description: 'Technical mastery of kettlebell lifts.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Clean and press', 'Snatch technique', 'Flow sequences'],
    prerequisites: ['micro_func_2'],
    popularityScore: 93,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_func_4',
    domainId: 'dom_func',
    tier: 'MICROCRED',
    title: 'Battle Rope Techniques (Exercises)',
    description: 'Advanced rope patterns and programming.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Advanced waves', 'Combine movements', 'Build power'],
    prerequisites: ['micro_func_3'],
    popularityScore: 84,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_func_5',
    domainId: 'dom_func',
    tier: 'MICROCRED',
    title: 'Band Techniques (Exercises)',
    description: 'Full body conditioning using resistance bands.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Band resistance', 'Accommodating resistance', 'Rehab basics'],
    prerequisites: ['micro_func_4'],
    popularityScore: 86,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'short_func_1',
    domainId: 'dom_func',
    tier: 'SHORT',
    title: 'Rumble FIT',
    description: 'Complete boxing for fitness certification.',
    durationLabel: '1–3 weeks',
    accredited: false,
    outcomes: ['Run boxing classes', 'Master mitt work', 'Ensure safety', 'Program rounds'],
    prerequisites: ['micro_func_1', 'micro_func_2'],
    popularityScore: 94,
    image: '/images/courses/Heading (3).png',
    price: 499
  },
  {
    id: 'short_func_2',
    domainId: 'dom_func',
    tier: 'SHORT',
    title: 'Suspension FIT',
    description: 'Instructor certification for suspension training.',
    durationLabel: '1–3 weeks',
    accredited: false,
    outcomes: ['Design suspension classes', 'Correct form', 'Modify for injuries', 'Teach progressions'],
    prerequisites: ['micro_func_1', 'micro_func_2'],
    popularityScore: 90,
    image: '/images/courses/Heading (3).png',
    price: 499
  },
  {
    id: 'short_func_3',
    domainId: 'dom_func',
    tier: 'SHORT',
    title: 'Kettlebell FIT',
    description: 'Become a certified Kettlebell instructor.',
    durationLabel: '1–3 weeks',
    accredited: false,
    outcomes: ['Teach KB classes', 'Master programming', 'Coach complex lifts', 'Ensure safety'],
    prerequisites: ['micro_func_1', 'micro_func_2'],
    popularityScore: 95,
    image: '/images/courses/Heading (3).png',
    price: 499
  },

  // --- Advanced Hypertrophy ---
  {
    id: 'byte_hyper_1',
    domainId: 'dom_hyper',
    tier: 'BYTE',
    title: 'The 3 mechanism\'s of Hypertrophy',
    description: 'Understanding tension, stress, and damage.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Identify mechanisms', 'Apply to training', 'Balance variables'],
    prerequisites: [],
    popularityScore: 91,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'byte_hyper_2',
    domainId: 'dom_hyper',
    tier: 'BYTE',
    title: 'The process of muscle hypertrophy, how, what happens',
    description: 'Biological processes of muscle repair and growth.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Explain synthesis', 'Understand satellite cells', 'Optimize recovery'],
    prerequisites: ['byte_hyper_1'],
    popularityScore: 89,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'byte_hyper_3',
    domainId: 'dom_hyper',
    tier: 'BYTE',
    title: 'Case studies, how train mechanism, techniques',
    description: 'Real-world examples of hypertrophy training.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Analyze case studies', 'Select techniques', 'Review results'],
    prerequisites: ['byte_hyper_2'],
    popularityScore: 87,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'micro_hyper_1',
    domainId: 'dom_hyper',
    tier: 'MICROCRED',
    title: 'Hypertrophy Techniques (Reps & Sets)',
    description: 'Optimizing volume and intensity for growth.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Program reps/sets', 'Calculate volume', 'Apply progressive overload'],
    prerequisites: ['byte_hyper_3'],
    popularityScore: 92,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_hyper_2',
    domainId: 'dom_hyper',
    tier: 'MICROCRED',
    title: 'Long Term Gains - Periodised Hypertrophy',
    description: 'Planning for sustained muscle growth over years.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Periodize for size', 'Avoid plateaus', 'Manage fatigue'],
    prerequisites: ['micro_hyper_1'],
    popularityScore: 90,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_hyper_3',
    domainId: 'dom_hyper',
    tier: 'MICROCRED',
    title: 'The Science of Time Under Tension (TUT)',
    description: 'Using tempo to maximize muscle stimulus.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Manipulate tempo', 'Understand TUT', 'Coach control'],
    prerequisites: ['micro_hyper_2'],
    popularityScore: 88,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_hyper_4',
    domainId: 'dom_hyper',
    tier: 'MICROCRED',
    title: 'Splits',
    description: 'Designing effective training splits for hypertrophy.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Design splits', 'Optimize frequency', 'Balance body parts'],
    prerequisites: ['micro_hyper_3'],
    popularityScore: 93,
    image: '/images/courses/Heading (3).png',
    price: 120
  },

  // --- Power Training ---
  {
    id: 'byte_power_1',
    domainId: 'dom_power',
    tier: 'BYTE',
    title: 'Power Training/Power Lifting/Olympic Lifting',
    description: 'Introduction to the three pillars of power development.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Distinguish disciplines', 'Identify key lifts', 'Understand goals'],
    prerequisites: [],
    popularityScore: 91,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'byte_power_2',
    domainId: 'dom_power',
    tier: 'BYTE',
    title: 'Benefits/why, examples daily living, sport, speed',
    description: 'Applying power concepts to everyday life and athletic performance.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Apply to daily life', 'Enhance sport speed', 'Explain benefits'],
    prerequisites: ['byte_power_1'],
    popularityScore: 89,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'micro_power_1',
    domainId: 'dom_power',
    tier: 'MICROCRED',
    title: 'Introduction to Power Training',
    description: 'Foundational concepts and safety in power training.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Ensure safety', 'Program basics', 'Assess readiness'],
    prerequisites: ['byte_power_2'],
    popularityScore: 90,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_power_2',
    domainId: 'dom_power',
    tier: 'MICROCRED',
    title: 'Basic Power Techniques (Exercises)',
    description: 'Mastering the fundamental movements for power.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Coach box jumps', 'Teach med ball throws', 'Correct form'],
    prerequisites: ['micro_power_1'],
    popularityScore: 92,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_power_3',
    domainId: 'dom_power',
    tier: 'MICROCRED',
    title: 'Olympic Lifting for Beginners',
    description: 'Starting the journey into the snatch and clean & jerk.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Perform hang clean', 'Execute power snatch', 'Drill positions'],
    prerequisites: ['micro_power_2'],
    popularityScore: 94,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_power_4',
    domainId: 'dom_power',
    tier: 'MICROCRED',
    title: 'Plyometric Training',
    description: 'Explosive jump training for speed and power.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Program plyometrics', 'Progress intensity', 'Minimize ground contact'],
    prerequisites: ['micro_power_3'],
    popularityScore: 88,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_power_5',
    domainId: 'dom_power',
    tier: 'MICROCRED',
    title: 'Velocity Based Training (VBT)',
    description: 'Using velocity metrics to autoregulate training loads.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Measure velocity', 'Adjust loads', 'Target specific traits'],
    prerequisites: ['micro_power_4'],
    popularityScore: 87,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'short_power_1',
    domainId: 'dom_power',
    tier: 'SHORT',
    title: 'Olympic Lifting',
    description: 'Comprehensive certification in Olympic weightlifting coaching.',
    durationLabel: '1–3 weeks',
    accredited: false,
    outcomes: ['Coach full lifts', 'Correct faults', 'Program for competition', 'Manage injuries'],
    prerequisites: ['micro_power_1', 'micro_power_2'],
    popularityScore: 96,
    image: '/images/courses/Heading (3).png',
    price: 499
  },

  // --- Outdoor Group Training ---
  {
    id: 'byte_outdoor_1',
    domainId: 'dom_outdoor',
    tier: 'BYTE',
    title: 'Benefits & Challenges of Outdoor Training',
    description: 'Navigating the pros and cons of training in nature.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['List benefits', 'Mitigate challenges', 'Sell the concept'],
    prerequisites: [],
    popularityScore: 85,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'byte_outdoor_2',
    domainId: 'dom_outdoor',
    tier: 'BYTE',
    title: 'Bodyweight regressons/progressions ideas',
    description: 'Adapting exercises for mixed-ability groups outdoors.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Scale pushups', 'Modify squats', 'Challenge advanced clients'],
    prerequisites: ['byte_outdoor_1'],
    popularityScore: 88,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'byte_outdoor_3',
    domainId: 'dom_outdoor',
    tier: 'BYTE',
    title: 'Workout fomat focus e.g. tabatta specific',
    description: 'Structuring high-intensity interval sessions for groups.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Run Tabata', 'Time intervals', 'Manage flow'],
    prerequisites: ['byte_outdoor_2'],
    popularityScore: 86,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'byte_outdoor_4',
    domainId: 'dom_outdoor',
    tier: 'BYTE',
    title: 'Novel equipment ideas',
    description: 'Creative use of environment and portable equipment.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Use park benches', 'Utilize hills', 'Incorporate bands'],
    prerequisites: ['byte_outdoor_3'],
    popularityScore: 84,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'byte_outdoor_5',
    domainId: 'dom_outdoor',
    tier: 'BYTE',
    title: 'Exciting examples around the world',
    description: 'Inspiration from successful outdoor fitness communities globally.',
    durationLabel: '1 hr',
    accredited: false,
    outcomes: ['Analyze case studies', 'Adapt ideas', 'innovate programming'],
    prerequisites: ['byte_outdoor_4'],
    popularityScore: 83,
    image: '/images/courses/Heading (3).png',
    price: 0
  },
  {
    id: 'micro_outdoor_1',
    domainId: 'dom_outdoor',
    tier: 'MICROCRED',
    title: 'Seasons, Weather and Safety',
    description: 'Risk management and programming for changing conditions.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Assess risk', 'Plan for heat/cold', 'Ensure hydration'],
    prerequisites: ['byte_outdoor_5'],
    popularityScore: 90,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_outdoor_2',
    domainId: 'dom_outdoor',
    tier: 'MICROCRED',
    title: 'Programming & Structure for Outdoor Group Training',
    description: 'Designing cohesive long-term programs for groups.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Periodize groups', 'Balance intensity', 'Retain members'],
    prerequisites: ['micro_outdoor_1'],
    popularityScore: 91,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_outdoor_3',
    domainId: 'dom_outdoor',
    tier: 'MICROCRED',
    title: 'Minimal or Equipment Free Training for Groups',
    description: 'delivering high-value sessions with zero gear.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Master bodyweight', 'Use partner drills', 'Maximize space'],
    prerequisites: ['micro_outdoor_2'],
    popularityScore: 89,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_outdoor_4',
    domainId: 'dom_outdoor',
    tier: 'MICROCRED',
    title: 'How to set up and Run an effective Bootcamp program',
    description: 'Business and operational side of running a bootcamp.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Market bootcamp', 'Manage signups', 'Create community'],
    prerequisites: ['micro_outdoor_3'],
    popularityScore: 92,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'micro_outdoor_5',
    domainId: 'dom_outdoor',
    tier: 'MICROCRED',
    title: 'Different formats YGIG, EMOM, Ladders, Ton Ups',
    description: 'Advanced session structures to keep engagement high.',
    durationLabel: '1–2 days',
    accredited: true,
    outcomes: ['Run YGIG', 'Program EMOMs', 'Design ladders'],
    prerequisites: ['micro_outdoor_4'],
    popularityScore: 88,
    image: '/images/courses/Heading (3).png',
    price: 120
  },
  {
    id: 'short_outdoor_1',
    domainId: 'dom_outdoor',
    tier: 'SHORT',
    title: 'Outdoor Bootcamp',
    description: 'Complete certification for outdoor group fitness instruction.',
    durationLabel: '1–3 weeks',
    accredited: false,
    outcomes: ['Lead large groups', 'Manage safety', 'Scale business', 'Create culture'],
    prerequisites: ['micro_outdoor_1', 'micro_outdoor_2'],
    popularityScore: 95,
    image: '/images/courses/Heading (3).png',
    price: 499
  }
];

export const ITEMS: Item[] = RAW_ITEMS.map(item => ({
  ...item,
  status: 'PUBLISHED',
  versionNumber: 1,
  lastPublishedAt: new Date().toISOString(),
  changelog: ['Initial release'],
  contentStructure: []
}));

export const MODULES: Module[] = [
  // Modules for 'Periodisation & Planning' (short_sc_1)
  { id: 'm-sc1-1', itemId: 'short_sc_1', title: 'The Macrocycle View', order: 1, type: 'VIDEO', estimatedMinutes: 45 },
  { id: 'm-sc1-2', itemId: 'short_sc_1', title: 'Mesocycle Structures', order: 2, type: 'READING', estimatedMinutes: 60 },
  { id: 'm-sc1-3', itemId: 'short_sc_1', title: 'Microcycle Variation', order: 3, type: 'VIDEO', estimatedMinutes: 40 },
  { id: 'm-sc1-4', itemId: 'short_sc_1', title: 'Case Study Assignment', order: 4, type: 'ACTIVITY', estimatedMinutes: 90 },

  // Modules for 'Systemised Personal Training' (short_fitbiz_1)
  { id: 'm-fb1-1', itemId: 'short_fitbiz_1', title: 'Defining Your SOPs', order: 1, type: 'VIDEO', estimatedMinutes: 30 },
  { id: 'm-fb1-2', itemId: 'short_fitbiz_1', title: 'Automation Tools', order: 2, type: 'READING', estimatedMinutes: 45 },
  { id: 'm-fb1-3', itemId: 'short_fitbiz_1', title: 'Client Onboarding Flow', order: 3, type: 'ACTIVITY', estimatedMinutes: 60 },
];

export const QUIZZES: Quiz[] = [
  // Quiz for 'Micros, Mesos & Macros' (micro_sc_1)
  {
    id: 'q-micro_sc_1',
    itemId: 'micro_sc_1',
    passMark: 80,
    attemptsAllowed: 3,
    timeLimitMinutes: 20,
    questions: [
      { id: 'q1', prompt: 'What is the largest training cycle?', options: ['Microcycle', 'Mesocycle', 'Macrocycle', 'Bicycle'], correctIndex: 2, tags: ['planning', 'basics'] },
      { id: 'q2', prompt: 'How long is a typical microcycle?', options: ['1 day', '1 week', '1 month', '1 year'], correctIndex: 1, tags: ['planning', 'timing'] },
      { id: 'q3', prompt: 'What characterizes a mesocycle?', options: ['Specific training block', 'Single workout', 'Annual plan', 'Warmup'], correctIndex: 0, tags: ['planning'] },
    ]
  },
  // Quiz for 'Periodisation & Planning' (short_sc_1)
  {
    id: 'q-short_sc_1',
    itemId: 'short_sc_1',
    passMark: 75,
    attemptsAllowed: 2,
    timeLimitMinutes: 45,
    questions: [
      { id: 'q1', prompt: 'Which phase emphasizes volume over intensity?', options: ['Competition', 'Peaking', 'General Prep', 'Rest'], correctIndex: 2 },
      { id: 'q2', prompt: 'Tapering involves:', options: ['Increasing volume', 'Reducing fatigue', 'Eating more', 'Sleeping less'], correctIndex: 1 },
      { id: 'q3', prompt: 'Linear periodization implies:', options: ['Random changes', 'Progressive overload', 'Daily undulation', 'No plan'], correctIndex: 1 },
    ]
  }
];
